# Generated by Django 2.2.26 on 2022-02-28 05:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0001_load_initial_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Approval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shape', models.TextField()),
                ('size', models.DecimalField(decimal_places=2, max_digits=3)),
                ('color', models.TextField()),
                ('clarity', models.TextField()),
                ('rap', models.IntegerField()),
                ('discount', models.SmallIntegerField()),
                ('price', models.BigIntegerField()),
                ('approval', models.TextField()),
                ('date', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
